# Generated by Django 5.0.6 on 2024-07-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Registro',
        ),
    ]
